# Generated by Django 5.1.6 on 2026-02-21 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_dailyactivity_breakfast_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='stress_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
